spring:
  application:
#  ????
    name: user-center
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yupi
      username: root
      password: Abin21428!!
server:
  port: 8080

